# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush, QPixmap
from PyQt5.QtWidgets import QMessageBox

from common._util import Backdrop, Home, Responses, History_LOG


class Ui_mainWindow(object):
    """
    主页面
    """
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(440, 380)
        mainWindow.setWindowOpacity(0.9)  # 设置窗口透明度
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 440, 380))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap(Backdrop))
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 200, 50))
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setStyleSheet("color: rgb(0, 0, 0);font: 18pt \"楷体\";")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 60, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 60, 20))
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 230, 60, 30))
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.input_host = QtWidgets.QLineEdit(self.centralwidget)
        self.input_host.setGeometry(QtCore.QRect(90, 100, 340, 30))
        self.input_host.setFont(font)
        self.input_host.setObjectName("input_host")
        self.input_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.input_phone.setGeometry(QtCore.QRect(90, 160, 340, 30))
        self.input_phone.setFont(font)
        self.input_phone.setObjectName("input_phone")
        self.input_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pwd.setGeometry(QtCore.QRect(90, 230, 340, 30))
        self.input_pwd.setFont(font)
        self.input_pwd.setObjectName("input_pwd")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(50, 300, 141, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.input_host.raise_()
        self.input_phone.raise_()
        self.input_pwd.raise_()
        self.send.raise_()
        self.pushButton_2.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "登录数据"))
        mainWindow.setWindowIcon(QtGui.QIcon(Home))   #设置icon
        self.label.setText(_translate("mainWindow", "登录URL获取数据"))
        self.label_3.setText(_translate("mainWindow", "  host"))
        self.label_6.setText(_translate("mainWindow", "用户名"))
        self.label_7.setText(_translate("mainWindow", "密 码"))
        self.input_host.setPlaceholderText('URL')
        self.input_phone.setPlaceholderText('手机号')
        self.input_pwd.setPlaceholderText('密码')
        self.send.setText(_translate("mainWindow", "发送"))
        self.pushButton_2.setText(_translate("mainWindow", "历史记录"))

class send_MainWindow(object):
    """
    返回数据窗口
    """

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 380)
        MainWindow.setWindowOpacity(0.9)  # 设置窗口透明度
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 440, 380))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap(Backdrop))
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(155, 2, 200, 60))
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setStyleSheet("color: rgb(0, 0,1);font: 24pt \"楷体\";")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.export_url = QtWidgets.QTextBrowser(self.centralwidget)
        self.export_url.setGeometry(QtCore.QRect(10, 190, 420, 80))
        self.export_url.setStyleSheet("font: 14pt \"宋体\";")
        self.export_url.setObjectName("textBrowser")
        self.export_pc = QtWidgets.QTextEdit(self.centralwidget)
        self.export_pc.setGeometry(QtCore.QRect(10, 130, 420, 35))
        self.export_pc.setStyleSheet("font: 14pt \"宋体\";")
        self.export_pc.setObjectName("export_url")
        self.export_token = QtWidgets.QTextEdit(self.centralwidget)
        self.export_token.setGeometry(QtCore.QRect(10,70, 420, 35))
        self.export_token.setStyleSheet("font: 14pt \"宋体\";")
        self.export_token.setObjectName("export_token")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 300, 205, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2.raise_()
        self.export_pc.raise_()
        self.export_url.raise_()
        self.export_token.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowIcon(QtGui.QIcon(Responses))  # 设置icon
        MainWindow.setWindowTitle(_translate("MainWindow", "接口返回信息"))
        self.label.setText(_translate("MainWindow", "接口数据"))
        self.pushButton.setText(_translate("MainWindow", "返回首页"))
class log_MainWindow(object):
    """
    历史记录数据窗口
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 380)
        MainWindow.setWindowOpacity(0.9)  # 设置窗口透明度
        # MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 设置窗口背景透明
        # self.label_2 = QtWidgets.QLabel(self.centralwidget)
        # self.label_2.setGeometry(QtCore.QRect(0, 0, 440, 380))
        # self.label_2.setTextFormat(QtCore.Qt.AutoText)
        # self.label_2.setPixmap(QtGui.QPixmap(Backdrop))
        # self.label_2.setScaledContents(False)
        # self.label_2.setWordWrap(False)
        # self.label_2.setObjectName("label_2")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(20, 0, 120, 40))
        # self.label_3.setStyleSheet("color: rgb(0, 0, 0);font: 24pt \"楷体\";")
        # self.label_3.setObjectName("label_3")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 440, 380))
        self.textBrowser.setObjectName("textBrowser")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setItalic(True)
        self.textBrowser.setFont(font)
        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(320, 8, 90, 30))
        # font = QtGui.QFont()
        # font.setFamily("楷体")
        # font.setPointSize(14)
        # self.pushButton.setFont(font)
        # self.pushButton.setObjectName("pushButton")
        # self.label_2.raise_()
        # self.label_3.raise_()
        # self.pushButton.raise_()
        self.textBrowser.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowIcon(QtGui.QIcon(History_LOG))  # 设置icon
        MainWindow.setWindowTitle(_translate("MainWindow", "历史操作记录"))
        # self.label_3.setText(_translate("MainWindow", "历史记录"))
        # self.pushButton.setText(_translate("MainWindow", "返回首页"))